services:
  myceliumd:
    # TODO: Replace with image soon
    # image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myceliumd
    restart: unless-stopped
    network_mode: host
    volumes:
      # Key file
      - ${MYCELIUM_KEY_FILE}:/private.key:z
      
      # - ${CONFIG_FILE_PATH}:/mycelium.conf:z

     # Access to TUN/TAP control device node
     - /dev/net/tun:/dev/net/tun:z
    cap_add:
      # Add capability for performing needed network
      # manipulation via the `/dev/tun` in order to
      # open tun adaptor
      - NET_ADMIN
      
    command:
      # NOTE: Don't change this unless you do the
      # same on the container-side for the key-file
      # volume-mount
      - "--key-file ${MYCECLIUM_KEY_FILE_CONTAINER_SIDE:-/private.key}"

    
      - "--${MYCELIUM_LOG_LEVEL:-silent}"
      # FIXME: Enable the below soon
      # - "--config-file ${MYCELIUM_CONFIG_FILE_PATH}"
      - "--peers {$MYCELIUM_PEERS_STRING}"

      # QUIC listening port
      - "--quic-listen-port ${MYCELIUM_QUIC_PORT:-9651}"

      # TCP listening port
      - "--tcp-listen-port ${MYCELIUM_TCP_PORT:-9651}"

      # Peer discovery (LAN multicast) port
      - "--peer-discovery-port ${MYCELIUM_PD_PORT:-9650}"

      # TUN adaptor name
      - "--tun-name ${MYCELIUM_TUN_IFNAME:-mycelium0}"
