services:
  myceliumd:
    # TODO: Replace with image soon
    # image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myceliumd
    restart: unless-stopped
    network_mode: host
    volumes:
      # Data directory (keys)
      - ${MYCELIUM_DATA_DIR}:/data:z
      
      # Access to TUN/TAP control device node
      - /dev/net/tun:/dev/net/tun:z
    cap_add:
      # Add capability for performing needed network
      # manipulation via the `/dev/tun` in order to
      # open tun adaptor
      - NET_ADMIN
    environment:
      # Setting to `debug` means -> `--debug`
      # and setting to `silen` means -> `--silent`
      - LOG_OPTION=${MYCELIUM_LOG_OPTION:-debug}

      - QUIC_PORT=${MYCELIUM_QUIC_PORT}
      - TCP_PORT=${MYCELIUM_TCP_PORT}
      - PD_PORT=${MYCELIUM_PD_PORT}
      - TUN_IFNAME=${MYCELIUM_TUN_IFNAME}
