# REMOVE/ADD COMMENT TO ENABLE/DISABLE LINE

peers = [
  "tcp://188.40.132.242:9651",
  "quic://[2a01:4f8:212:fa6::2]:9651",
  "quic://185.69.166.7:9651",
  "tcp://[2a02:1802:5e:0:8c9e:7dff:fec9:f0d2]:9651",
  "quic://65.21.231.58:9651",
  "tcp://[2a01:4f9:5a:1042::2]:9651",
]
api_addr = "127.0.0.1:8989"
tcp_listen_port = 9651
quic_listen_port = 9651
tun_name = "mycelium"
disable_peer_discovery = false
no_tun = false
#metrics_api_address = 0.0.0.0:9999
#firewall_mark = 30

## Options below only apply when myceliumd-private is used
#network_name = "private network name"
#network_key_file = "path_to_key_file"
